name: "Get & Cache Dependenceies"
description: Get the code depenpendencies and cache them for future use.
inputs:
  caching:
    description: "Wether to cache the dependencies or not"
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: npm ci
      shell: bash
