name: Lint, Test, and Deploy
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm install
              working-directory: 04 Practice Project (Start)
            - name: Run esling
              run: npm run lint
              working-directory: 04 Practice Project (Start)
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm install
              working-directory: 04 Practice Project (Start)
            - name: Run tests
              run: npm test
              working-directory: 04 Practice Project (Start)
    deploy:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm install
              working-directory: 04 Practice Project (Start)
            - name: Build project
              run: npm run build
              working-directory: 04 Practice Project (Start)
            - name: Deploy to server
              run: |
                  echo "Deploying to server..."
                  # Add your deployment commands here