name: First Workflow
on: workflow_dispatch

jobs:
  fiirst-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: |
          echo "Hello, World!"
          echo "This is my first GitHub Action workflow."
      - name: Print Goodbye
        run: |
          echo "Done!"