name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        default: dist
        description: Name of the deployable artifact files
        required: false
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    #     description: A secret required for deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: |
          echo "Listing files in the current directory:"
          ls -la
      - name: Output information
        run: |
          echo "Deploying and uploading ..."
